import Head from 'next/head'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import MediumCard from '../components/MediumCard'
import SmallCard from '../components/SmallCard'

export default function Home({ exploreData, cardsData }) {
  return (
    <div>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main className='px-8 mx-auto max-w-7xl sm:px-16'>
        <section className='pt-6'>
          <h2 className='pb-5 text-4xl font-semibold'>Explore Nearby</h2>
          {/*Pull in data from the server - API endpoint*/}
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {
              exploreData.map((item) => (
                <SmallCard key={item.img} img={item.img} location={item.location} distance={item.distance} />
              ))
            }
          </div>
        </section>
        <section>
          <h2 className='py-8 text-4xl font-semibold'>Live Anywhere</h2>
          <div className='flex p-3 -ml-3 space-x-4 overflow-scroll scrollbar-hide'>
            {
              cardsData.map(item => (
                <MediumCard key={item.img} img={item.img} title={item.title} />
              ))
            }
          </div>
        </section>
        <LargeCard img="https://links.papareact.com/4cj" title="The Greatest Outdoors" description="Wishlists curated by Airbnb" buttonText="Got Inspired" />
      </main>
      <Footer />
    </div>
  )
};

export const getStaticProps = async (ctx) => {
  const exploreData = await fetch("https://links.papareact.com/pyp").then(res => res.json());
  const cardsData = await fetch("https://links.papareact.com/zp1").then(res => res.json());
  return {
    props: {
      exploreData, cardsData,
    }
  }
}


