import { useRouter } from 'next/router';
import React from 'react';
import Footer from '../components/Footer';
import Header from '../components/Header';
import InfoCards from '../components/InfoCards';
import Map from '../components/Map';
import Head from 'next/head';

function Search({ searchResults }) {
     const router = useRouter();
     const { location, startDate, endDate, noOfGuersts } = router.query;
     const range = `${startDate.slice(4, startDate.length)} - ${endDate.slice(4, endDate.length)}`;
     return (
          <div>
               <Head>
                    <title>{router.query.location ? `Airbnb Search - ${router.query.location}` : "Location"}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
               </Head>
               <Header placeholder={`${location} | ${range} | ${noOfGuersts} guests`} />
               <main className="flex">
                    <div className='flex-grow px-6 pt-14'>
                         <p className='text-xs'>300+ Stays - {range} - for {noOfGuersts} guests</p>
                         <h1 className='mt-2 mb-6 text-3xl font-semibold'>Stays in {location}</h1>
                         <div className='hidden mb-5 space-x-3 text-gray-800 md:inline-flex whitespace-nowrap'>
                              <p className='button'>Cancallation Flexibility</p>
                              <p className='button'>Type of Place</p>
                              <p className='button'>Price</p>
                              <p className='button'>Rooms of Beds</p>
                              <p className='button'>More fillters</p>
                         </div>
                         {
                              searchResults.map(({ img, title, description, lat, location, long, price, star, total }) => (
                                   <InfoCards key={img} img={img} title={title} description={description} lat={lat} location={location} price={price} long={long} star={star} total={total} />
                              ))
                         }
                    </div>
                    <div className='xl:inline-flex xl:min-w-[600px]'>
                         <Map searchResults={searchResults} />
                    </div>
               </main>
               <Footer />
          </div>
     )
}

export default Search;

export const getServerSideProps = async (ctx) => {
     const searchResults = await fetch("https://links.papareact.com/isz").then(res => res.json());

     return {
          props: {
               searchResults,
          }
     }
}
